#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanTimeDirectories

rm -rf postProcessing
rm -rf VTK
rm -rf ./log ./log.*

#------------------------------------------------------------------------------
